import { Status } from '../enums';
import { IArticle } from '../interfaces';

const mockArticle: IArticle = {
  id: '1',
  documentId: '1',
  title: 'Sample Article',
  slug: 'article-1',
  excerpt: 'This is a sample article excerpt.',
  content: 'This is the content of the sample article.',
  author: 'John Doe',
  featuredImage: {
    url: '/images/sample.jpg',
    alternativeText: 'Sample Image',
    formats: {
      small: {
        url: '/images/sample-small.jpg',
        width: 400,
        height: 300,
        ext: '',
        hash: '',
        mime: '',
        name: '',
        path: '',
        size: 0,
        sizeInBytes: 0,
      },
      medium: {
        url: '/images/sample-medium.jpg',
        width: 800,
        height: 600,
        ext: '',
        hash: '',
        mime: '',
        name: '',
        path: '',
        size: 0,
        sizeInBytes: 0,
      },
      large: {
        url: '/images/sample-large.jpg',
        width: 1200,
        height: 900,
        ext: '',
        hash: '',
        mime: '',
        name: '',
        path: '',
        size: 0,
        sizeInBytes: 0,
      },
      thumbnail: {
        ext: '',
        hash: '',
        height: 0,
        mime: '',
        name: '',
        path: '',
        size: 0,
        sizeInBytes: 0,
        url: '',
        width: 0,
      },
    },
    caption: '',
    id: '',
    documentId: '',
    name: '',
    width: 0,
    height: 0,
  },
  categories: [
    {
      id: '1',
      name: 'Category 1',
      slug: 'category-1',
      documentId: '',
      articles: [],
    },
  ],
  locale: 'en',
  status: Status.PUBLISHED,
  createdAt: '2023-01-01T00:00:00Z',
  updatedAt: '2023-01-02T00:00:00Z',
  publishedAt: '2023-01-03T00:00:00Z',
};

export default mockArticle;
